version: "3.0"
services:
  rasa:
    image: rasa/rasa:3.6.8-full
    ports:
      - 5005:5005
    volumes:
      - ./:/app
      - ./models:/app/models
    command:
      - run
      - --cors
      - "*"

  app:
    image: kakhi/bookbot:v21
    ports:
      - 5055:5055

  frontend:
    image: nginx:1.21.3-alpine
    ports:
      - 80:80
    volumes:
      - ../frontend:/usr/share/nginx/html
      - ../frontend/default.conf:/etc/nginx/conf.d/default.conf
